#!/bin/sh

set -e

dir=$(dirname "$0")

for image in \
	make \
	dnsmasq \
	ntpd \
	ldap \
	squid \
	gitlab \
	jre \
	nexus \
	jenkins \
	dropbear \
	jdk \
	jenkins-mvn \
	dropbear-mvn \
	sonar \
	prometheus \
	alertmanager \
	blackbox-exporter \
	node-exporer \
	grafana \
	elasticsearch \
	logstash \
	kibana \
	postgresql \
	ssdb \
	hbase \
	scylladb \
	gluster \
	heketi \
	nuster \
	metallb \
	ansible
do
	if [ -x "$dir/$image/build" ]; then
		printf 'Building %s...\n' "$image"
		"$dir/$image/build"
	fi
done
