#!/bin/sh

set -e

dir=$(dirname "$0")

for image in \
	jre \
	jenkins \
	dropbear \
	jdk \
	jenkins-mvn \
	dropbear-mvn \
	nexus \
	sonar \
	gitlab \
	prometheus \
	alertmanager \
	blackbox-exporter \
	node-exporer \
	grafana \
	elasticsearch \
	logstash \
	kibana
do
	if [ -x "$dir/$image/build" ]; then
		printf 'Building %s...\n' "$image"
		"$dir/$image/build"
	fi
done
