#!/bin/sh

# based on https://github.com/docker-library/openjdk/blob/master/8/jre/alpine/Dockerfile

set -e

. "$(dirname "$0")/../.common/fn"

check <<\EOF
version=$(apk search --no-cache openjdk8-jre-base | awk '
$1 != "fetch" && /^openjdk8-jre-base-/ {
	sub(/^openjdk8-jre-base-/, "")
	print
}
')
EOF

build <<EOF
FROM alpine:$alpine

RUN apk add --no-cache openjdk8-jre-base
EOF
